server:
  port: 8102
spring:
  application:
    name: king-biz-user
  profiles:
    include: db
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
