server:
  port: 8101
spring:
  application:
    name: king-biz-user
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
feign:
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000
#ribbon的超时时间
ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 4000
swagger:
  base-package: com.king4cloud.king.biz.user
app:
  id: king-biz-user