server:
  port: 8761
spring:
  application:
    name: king-center
eureka:
  instance:
    hostname: center1
    lease-expiration-duration-in-seconds: 15  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除 默认90
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: true #false:不作为一个客户端注册到注册中心
    fetch-registry: true #表示是否从 Eureka Server 获取注册信息，默认为 true。
    service-url:
      defaultZone: http://center2:8762/eureka/,http://center3:8763/eureka/
  server:
    enable-self-preservation: false #自我保护模式
    eviction-interval-timer-in-ms: 3000
