server:
  port: 8801
spring:
  application:
    name: king-zuul
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
zuul:
  routes:
    user:
      path: /api-user/**
      serviceId: king-biz-user
    account:
      path: /api-account/**
      serviceId: king-biz-account
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 4000
