server:
  port: 8201
spring:
  application:
    name: king-biz-account
  profiles:
    include: db
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
swagger:
  base-package: com.king4cloud.king.biz.account